Repository SiKreuz/discord-birthday-bot, pull requests merged in 2020-11, with the labels that each got.

#9 Multi language support
  .gitignore
  MANIFEST.in
  discord_birthday_bot/__init__.py
  discord_birthday_bot/config_util.py
  discord_birthday_bot/database_util.py
  discord_birthday_bot/date_util.py
  discord_birthday_bot/locale/de/LC_MESSAGES/discord_birthday_bot.po
  discord_birthday_bot/locale/discord_birthday_bot.pot
  discord_birthday_bot/main.py
  discord_birthday_bot/output_util.py
  setup.py
  src/date_util.py
Labels: feature

#10 Fixed wrong config path on windows
  discord_birthday_bot/config_util.py
Labels: bug

#13 Automatic update for birthday list
  .gitignore
  discord_birthday_bot/database_util.py
  discord_birthday_bot/locale/de/LC_MESSAGES/discord_birthday_bot.po
  discord_birthday_bot/locale/discord_birthday_bot.pot
  discord_birthday_bot/main.py
Labels: feature

#14 Hotfix: Congratulations & german translation fix
  discord_birthday_bot/locale/de/LC_MESSAGES/discord_birthday_bot.po
  discord_birthday_bot/main.py
Labels: bug, hotfix

#15 User can enter only day and month and date gets still saved
  discord_birthday_bot/database_util.py
  discord_birthday_bot/date_util.py
  discord_birthday_bot/main.py
  requirements.txt
  setup.py
Labels: feature

#16 Fixed bug when sending birthday messages - Feature: Date with no year
  discord_birthday_bot/main.py
Labels: bug

#17 Ping everyone on congratulation
  discord_birthday_bot/main.py
Labels: feature, improvement

#19 Bot prefix from parameter / config
  discord_birthday_bot/config_util.py
  discord_birthday_bot/main.py
Labels: feature, improvement

#18 Congratulate directly when birthday was set on the current day
  discord_birthday_bot/date_util.py
  discord_birthday_bot/main.py
Labels: feature, improvement
